name: Check hierarchy 

on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Hierarchy checker
        run: |
          python3 check_hierarchy.py
  